### ISSUE TITLE
'Workbench early startup' error

### ISSUE THREAD

**Issue by brooky1010** [KazeJiyu/eclipse-discord-integration#49]
Since I installed this it keeps giving me this error on startup:
`An internal error occurred during: "Workbench early startup".

There is an incompatible JNA native library installed on this system
Expected: 5.1.0
Found:    4.0.1`

I'm using the latest Eclipse Photon
I tried updating my Java but that didn't help.

EDIT: I'm on Windows 10 64-bit

Thanks

**Comment by brooky1010** [comment]
``An internal error occurred during: "Workbench early startup".


There is an incompatible JNA native library installed on this system
Expected: 5.1.0
Found:    4.0.1``

**Comment by KazeJiyu** [comment]
I'll try to investigate this issue. It is likely caused by the library I use to interact with Discord, though, so I don't know if I will be able to solve this.

Can you tell me which versions of Java you have tried ? Also, just in case, if you're using a JRE can you test to launch Eclipse IDE with a JDK instead ? I didn't try with Java 9+ yet, but it should work fine with a JDK 1.8.

**Comment by brooky1010** [comment]
My current Java version is Java 8 Update 181 (build 1.8.0_181-b13). I was using JRE but switched to JDK now and it still doesn't work.

**Comment by KazeJiyu** [comment]
Sadly I cannot reproduce your error. According to what I have found, it could be caused by the use of JNA by another Java program in your system.

That being said, it could have a simple fix. Could you try to open the _eclipse.ini_ file which is located next to _eclipse.exe_ and then to modify it in order to set the `jna.nosys` to true as follows ?
```
-vmargs
-Djna.nosys=true
```
The `-vmargs` line should already exist, otherwise you can append it at the end of the file.

If that fixes the issue I'll try to set the property programmatically so that it should not occur thereafter.

**Comment by brooky1010** [comment]
Yup, that seems to fix it for now. Thank you!
